export default function Footer() {
  return (
    <div className="flex flex-col bg-[#D7CCC8] border-t border-[#3E2723] p-8 md:p-12 text-black">
      <h1 className="text-center text-xl italic">
        "Vladimir’s biscuits are kneaded with love—literally!"
      </h1>
      <div className="flex flex-col my-4">
        <span className="text-center">
          © 2025 Vladimir’s Biscuit Business | Designed with paws and passion by
        </span>
        <span className="text-center">Xander Juneau</span>
        <span className="text-center text-xs italic">Images generated by ChatGPT</span>
      </div>
    </div>
  );
}
